travel/apps/destinations/urls.py
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import path

from apps.accounts.models import CustomerUser
from apps.destinations.charts import (
    BookingCharts,
    DashboardIndex,
    DestinationCharts,

)
from apps.destinations.views.visitor import (
    VisitorView,
)

from apps.destinations.views.destination import (
    AgencyAddView,
    AgencyDeleteView,
    AgencyAddExistingUserView,
    AgencyUpdateView,
    AgencyView,
    DestinationListView,
    DestinationCreateView,
    DestinationDetailView,
    DestinationUpdateView,
    DestinationDeleteView,
    GalleryListView,
    VideoListView,
    OptionTabDataTemplateAjaxView,
    ItineraryCreateView,
    ItineraryUpdateView,
    ItineraryView,
    RequestDeleteView,
    RequestManagerView,
    RequestProcessView,
    RequestView,
    SocialNetworkListView,
    SocialNetworkUpdateView,
    MailboxView,
    MailboxAdd,
    MailboxReply,
    MailboxDetail,
    MailboxSent,
    messageView,
    LeaderView,
    LeaderAddView,
    LeaderAddExistingUserView,
    LeaderDeleteView,
    DocumentView,
    DocumentAdd,
    DocumentUpdateView,
    FileDocumentsView,
    SearchDocumentsView
)

from apps.destinations.views.booking import (
    BookingListView,
    BookingSaveStat,
    UpdateBooking
)

from apps.destinations.views.maps import (
    DestinationMapView,
    MapListView,
)


def nocommunity_access(function=None, redirect_field_name=REDIRECT_FIELD_NAME, login_url=None):
    actual_decorator = user_passes_test(
        lambda u: u.is_authenticated,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    nocom_decorator = user_passes_test(
        lambda u: u.is_authenticated and not u.is_community,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    if function:
        return actual_decorator(function) and  nocom_decorator(function)
    return actual_decorator and nocom_decorator



app_name = 'destinations'
urlpatterns = [
    path(
        '',
        nocommunity_access(DashboardIndex),
        name='dashboard-index',
    ),
    path(
        'documents',
        nocommunity_access(DocumentView.as_view()),
        name='documents',
    ),
    path('documents/add/',
        nocommunity_access(DocumentAdd.as_view()),
        name='documents-add'
    ),
    path(
        'documents/delete',
        nocommunity_access(DocumentView.as_view()),
        name='documents-delete',
    ),
    path(
        'documents/<int:pk>/update/',
        nocommunity_access(DocumentUpdateView.as_view()),
        name='documents-update',
    ),
    path(
        'files/',
        nocommunity_access(FileDocumentsView.as_view()),
        name='files-documents',
    ),
    path(
        'files/search',
        nocommunity_access(SearchDocumentsView.as_view()),
        name='files-search',
    ),
    path(
        'managers',
        nocommunity_access(LeaderView.as_view()),
        name='manager',
    ),
    path(
        'managers/add/existing',
        nocommunity_access(LeaderAddExistingUserView.as_view()),
        name='manager-add-existing'
    ),
    path(
        'managers/add/',
        nocommunity_access(LeaderAddView.as_view()),
        name='manager-add',
    ),
    path(
        'managers/<int:pk>/delete',
        nocommunity_access(LeaderDeleteView.as_view()),
        name='manager-delete'
    ),
    path(
        'agencies/list',
        nocommunity_access(AgencyView.as_view()),
        name='agencies',
    ),
    path(
        'agencies/add/existing',
        nocommunity_access(AgencyAddExistingUserView.as_view()),
        name='agency-add-existing'
    ),
    path(
        'agencies/add',
        nocommunity_access(AgencyAddView.as_view()),
        name='agency-add'
    ),
    path(
        'agencies/<int:pk>/delete',
        nocommunity_access(AgencyDeleteView.as_view()),
        name='agency-delete'
    ),

    path(
        'agencies/<int:pk>/',
        nocommunity_access(AgencyUpdateView.as_view()),
        name='agency-edit'
    ),
    path(
        'mailbox',
        nocommunity_access(MailboxView.as_view()),
        name='mailbox',
    ),
    path(
        'mailbox/sent',
        nocommunity_access(MailboxSent.as_view()),
        name='mailbox-sent',
    ),
    path(
        'mailbox/delete-mail',
        nocommunity_access(MailboxView.as_view()),
        name='delete-mail',
    ),
    path(
        'mailbox/add',
        nocommunity_access(MailboxAdd.as_view()),
        name='mailbox-add',
    ),
    path(
        'mailbox/reply/<int>',
        nocommunity_access(MailboxReply.as_view()),
        name='mailbox-reply',
    ),
    path(
        'mailbox/<int>',
        nocommunity_access(MailboxDetail.as_view()),
        name='mailbox-detail'
    ),

    path(
        'list',
        nocommunity_access(DestinationListView.as_view()),
        name='list',
    ),

    path(
        'create/',
        nocommunity_access(DestinationCreateView.as_view()),
        name='create',
    ),

    path(
        '<int:pk>/create/',
        nocommunity_access(DestinationDetailView.as_view()),
        name='detail',
    ),

    path(
        '<int:pk>/update/',
        nocommunity_access(DestinationUpdateView.as_view()),
        name='update',
    ),

    path(
        '<int:pk>/delete/',
        nocommunity_access(DestinationDeleteView.as_view()),
        name='delete',
    ),

    path(
        'social-network/',
        nocommunity_access(SocialNetworkListView.as_view()),
        name='social-network',
    ),
    path(
        'social-network/delete-setting',
        nocommunity_access(SocialNetworkListView.as_view()),
        name='delete-setting',
    ),
    path(
        '<int:pk>/up/',
        nocommunity_access(SocialNetworkUpdateView.as_view()),
        name='update-social',
    ),

    path(
        '<int:pk>/gallery/',
        nocommunity_access(GalleryListView.as_view()),
        name='gallery-list',
    ),

    path(
        '<int:pk>/video/',
        nocommunity_access(VideoListView.as_view()),
        name='video-list',
    ),

    path(
        'option/<int:pk>/template/',
        nocommunity_access(OptionTabDataTemplateAjaxView.as_view()),
        name='option-template',
    ),

    path(
        'itinerary/get-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='get-itinerary',
    ),

    path(
        'itinerary/add-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='add-itinerary',
    ),
    path(
        'itinerary/update-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='update-itinerary',
    ),
    path(
        'itinerary/delete-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='delete-itinerary',
    ),
    path(
        'itinerary/create/',
        nocommunity_access(ItineraryCreateView.as_view()),
        name='itinerary-create',
    ),
    path(
        'itinerary/<pk>/edit/',
        nocommunity_access(ItineraryUpdateView.as_view()),
        name='itinerary-edit',
    ),

    path(
        'itinerary/',
        nocommunity_access(ItineraryView.as_view()),
        name='itinerary-list',
    ),

    path(
        'booking-list/',
        nocommunity_access(BookingListView.as_view()),
        name='booking-list',
    ),

    path(
        'booking-charts/',
        nocommunity_access(BookingCharts),
        name='booking-charts',
    ),

    path(
        'booking-save/',
        nocommunity_access(BookingSaveStat.as_view()),
        name='booking-save',
    ),

    path(
        'update-booking/',
        nocommunity_access(UpdateBooking.as_view()),
        name='update-booking',
    ),

    path(
        'destination-charts/',
        nocommunity_access(DestinationCharts),
        name='destination-charts',
    ),

    path(
        'maps/get-list',
        nocommunity_access(MapListView.as_view()),
        name='list-maps',
    ),

    path(
        'maps/add-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='add-map',
    ),
    path(
        'maps/update-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='update-map',
    ),
    path(
        'maps/delete-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='delete-map',
    ),


    path(
        'maps/',
        nocommunity_access(DestinationMapView.as_view()),
        name='destination-map',
    ),

    path(
        'message/',
        nocommunity_access(messageView.as_view()),
        name='send_message',
    ),

    path(
        'requests/manager',
        nocommunity_access(RequestManagerView.as_view()),
        name='requests_manager',
    ),
    path(
        'requests/<int:pk>/approve/',
        nocommunity_access(RequestProcessView.as_view(action='approve')),
        name='requests_approve',
    ),

    path(
        'requests/<int:pk>/reject/',
        nocommunity_access(RequestProcessView.as_view(action='reject')),
        name='requests_reject',
    ),

    path(
        'requests/<int:pk>/delete/',
        nocommunity_access(RequestDeleteView.as_view()),
        name='requests_delete',
    ),

    path(
        'requests/',
        nocommunity_access(RequestView.as_view()),
        name='requests',
    ),

    path(
        'visitor/',
        nocommunity_access(VisitorView.as_view()),
        name='visitor',
    ),
]

travel/apps/payments/paypal/urls.py
from django.urls import path

from apps.payments.paypal.views import CancelRedirectView, ApproveRedirectView

app_name = 'paypal'
urlpatterns = [
    path(
        'subscription/approved',
        ApproveRedirectView.as_view(),
        name='subscription-approved',
    ),

    path(
        'subscription/cancel',
        CancelRedirectView.as_view(),
        name='subscription-cancel',
    ),

]

travel/config/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django_js_reverse import views
from apps.landing_page.views import (
    CategoriesView,
    DetailDestinationView,
    SaveSearchView,
    DeleteRegisterView,
    PrivacySettingView,
    getItineraryPDF,
    ContactUs,
)

from apps.destinations.views.booking import BookingSaveView
from django.contrib.auth.decorators import login_required
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500
)


#import notifications.urls

admin.autodiscover()

urlpatterns = [
    url(
        r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}},
    ),

    url(
        r'^rosetta/',
        include('rosetta.urls'),
    ),

    path(
        'api/',
        include('apps.api.urls', namespace='api'),
    ),

    path(
        'ratings/',
        include('star_ratings.urls', namespace='ratings')
    ),

    url(
        r'^jsreverse/$',
        views.urls_js, name='js_reverse'
    ),
]

urlpatterns += i18n_patterns(
    url(
        r'^nested_admin/',
        include('nested_admin.urls'),
    ),

    url(
        r'^admin/',
        admin.site.urls,
    ),

    url(
        r'^impersonate/',
        include('impersonate.urls'),
    ),

    path(
        'summernote/',
        include('django_summernote.urls'),
    ),

    url(
        r'^accounts/',
        include("apps.accounts.urls", namespace='accounts'),
    ),

    path(
        'directmessages/',
        include("apps.directmessages.urls")
    ),

    url(
        r'^category/destination/(?P<slug>\w+)',
        DetailDestinationView.as_view(),
        name='view_detail_destination',
    ),

    url(
        r'^search/',
        CategoriesView.as_view(),
        name='search_category',
    ),

    url(
        r'^category/(?P<alias>\w+)',
        CategoriesView.as_view(),
        name='view_category',
    ),

    path(
        'community/',
        include('apps.community.urls'),
        name='community',
    ),

    path(
        'paypal/',
        include('apps.payments.paypal.urls'),
    ),

    path(
        'dashboard/',
        include("apps.destinations.urls",
                namespace='dashboard'),
    ),

    path(
        'advertisements/',
        include("apps.advertisements.urls",
                namespace='advertisements'),
    ),

    path(
        'personal-search/',
        SaveSearchView.as_view(),
        name='personal-search',
    ),

    path(
        'make-booking/',
        BookingSaveView.as_view(),
        name='make-booking',
    ),

    path(
        'delete-register/',
        DeleteRegisterView.as_view(),
        name='delete-register',
    ),

    path(
        'setting-privacy/',
        PrivacySettingView.as_view(),
        name='setting-privacy',
    ),

    url(r'^get-itinerary/(?P<slug>\w+)',
        getItineraryPDF.as_view(),
        name='get_itinerary'),

    url(r'contact-us',
        ContactUs.as_view(),
        name='contact-us'),

    url(
        r'^',
        include('cms.urls'),
        name='index',
    ),

    #url('^inbox/notifications/',
    #    include(notifications.urls, namespace='notifications')),


)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom Defaults Pages https://docs.djangoproject.com/en/2.1/ref/views/#error-views
handler400 = 'apps.landing_page.views.pag_400_bad_request'
handler403 = 'apps.landing_page.views.pag_403_permission_denied'
handler404 = 'apps.landing_page.views.pag_404_page_not_found'
handler500 = 'apps.landing_page.views.pag_500_server_error'

travel/apps/destinations/views/maps.py
import logging
from django.http import JsonResponse
from django.utils.translation import gettext_lazy as _
from django.shortcuts import (
    render,
    get_object_or_404,
)
from django.http import QueryDict
from apps.destinations.forms import DestinationMapForm

from apps.destinations.models import Destination, DestinationMap
from django.views.generic import (
    View,
)
from apps.destinations.serializers import (
    MapSerializer,
    mapped_errors_form,
)

from apps.utils.mixins import NoCommunityRequiredMixin

logger = logging.getLogger(__name__)

class DestinationMapView(NoCommunityRequiredMixin, View):
    def get(self, request):
        form_map =  DestinationMapForm()
        form_map.fields['destination'].queryset = Destination.objects.filter(
                user=request.user,
                map=None)
        destination = DestinationMap.objects.filter(destination__user=request.user.id)
        return render(request,'destinations/map/maps.html',{'form_map':form_map, 'destination':destination})

    def post(self,request):
        form_map = DestinationMapForm(request.POST)
        if form_map.is_valid():
            if form_map.save() :
                destination = DestinationMap.objects.filter(destination__user=request.user.id)
                return render(request,'destinations/map/maps.html',{'form_map':form_map, 'destination':destination})
        else:
            return JsonResponse(
                {
                'error':mapped_errors_form(form_map),
                'status':False
                },
                safe=False,
            )

    def delete(self,request):
        pk_map= QueryDict(request.body)
        maps = get_object_or_404(DestinationMap, pk=pk_map['pk'])
        if maps.delete() :
            return JsonResponse(
                {
                'status':True
                },
                safe=False,
            )


class MapListView(View):
    def get(self, request):
        if request.is_ajax():
            if 'destiny' in request.GET:
                maps = DestinationMap.objects.all() \
                .filter(destination__user=request.user.id) \
                .filter(destination=request.GET['destiny'])
                return JsonResponse(
                    MapSerializer(maps),
                    safe=False,
                    )
            else:
                return JsonResponse({},
                    safe=False,
                    )

travel/apps/destinations/views/visitor.py
from django.contrib.gis.geoip2 import GeoIP2
from django.conf import settings
from django.http import JsonResponse
from django.views.generic import (
    View,
)
from django.utils.translation import gettext_lazy as _

from apps.destinations.models import (
	Destination,
	DestinationVisitor
)
from apps.destinations.utils import get_client_ip

class VisitorView(View):
    def get(self, request):
    	geo_ip = GeoIP2()
    	if settings.DEBUG :
    		ip_visitor = "72.14.207.99"
    		data_visitor = geo_ip.city(ip_visitor)
    	else:
    		ip_visitor = get_client_ip(request)
    		data_visitor = geo_ip.city(str(ip_visitor))
    	try:
	    	DestinationVisitor.objects.create(
	    		destination = Destination.objects.get(pk=request.GET['destination']),
	    		ip_address  = ip_visitor,
	    		dma_code =data_visitor['dma_code'] ,
	    		country_code = data_visitor['country_code'],
	    		country_name =data_visitor['country_name']
	    	)
	    	return JsonResponse({},safe=False,status=200)
    	except Exception as e:
    		return JsonResponse({},safe=False,status=500)

travel/apps/destinations/templates/dashboard/mailbox/_mailboxReply.html
{% extends 'destinations/base.html' %}
{% load static i18n destinations_tags static %}
{% block title %}{% trans 'Mailbox - Travelposting' %}{% endblock %}
{% block extracss %}
<!-- FooTable -->
<link href="{% static 'dashboard/css/plugins/iCheck/custom.css' %}" rel="stylesheet">
<link href="{% static 'dashboard/extras/summernote/summernote.min.css'%}" rel="stylesheet">
<link href="{% static 'dashboard/css/plugins/select2/select2.min.css' %}" rel="stylesheet">
<link href="{% static 'dashboard/css/plugins/select2/select2-bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extracss%}
{% block content %}
<div id="page-wrapper" class="gray-bg">
    {% include 'destinations/navbar_top.html' %}
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-3">
                {% include 'dashboard/mailbox/mailbox_menu_left.html' %}
            </div>
            <div class="col-lg-9 animated fadeInRight">
                <div class="mail-box-header">
                    <h2>
                        {% trans "Reply message to " %}<b>{{ mensaje.sender }}</b>
                    </h2>
                </div>
                <div class="mail-box">
                    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
                        <div class="mail-body">
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label"><b>{% trans "Subject" %}:</b></label>
                                    <div class="col-sm-10"><input type="text" disabled name="subject" class="form-control" value="Rw: {{ mensaje.subject}}"></div>
                                </div>
                        </div>
                        <div class="mail-text h-200">
                            <div class="form-group ">
                                <label class="col-sm-2 col-form-label"><b>{% trans "Message" %}:</b></label>
                                <textarea id="summernote" name="message"></textarea>
                            </div>
                            <div class="clearfix"></div>
                        </div>
                        <div class="mail-body">
                            <div class="form-group row">
                                <label><b>{% trans "Attach file"%}</b></label>
                                <div class="custom-file">        
                                    <input type="file" name="attach">
                                </div> 
                            </div>
                        </div>
                        <div class="mail-body text-right tooltip-demo">
                            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-reply"></i> {% trans "Send" %}</button>
                            <a href="{% url 'dashboard:mailbox' %}" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> {% trans "Discard" %}</a>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>


    {% include 'destinations/footer.html' %}
</div>
{% endblock content %}
{% block extrajs%}
<!-- SUMMERNOTE -->
<script src="{% static 'dashboard/extras/summernote/summernote.min.js' %}"></script>
<script src="{% static 'dashboard/js/plugins/select2/select2.full.min.js' %}"></script>
<script>

    $(document).ready(function () {
        $(".select2_demo_2").select2({
            theme: 'bootstrap4',
        });
        $('#summernote').summernote({
            height: 200,
            tooltip: false,
            focus: true,
        });

    });
</script>
{% endblock extrajs %}

travel/apps/destinations/templates/dashboard/mailbox/_mailboxadd.html
{% extends 'destinations/base.html' %}
{% load static i18n destinations_tags static %}
{% block title %}{% trans 'Mailbox - Travelposting' %}{% endblock %}
{% block extracss %}
<!-- FooTable -->
<link href="{% static 'dashboard/css/plugins/iCheck/custom.css' %}" rel="stylesheet">
<link href="{% static 'dashboard/extras/summernote/summernote.min.css'%}" rel="stylesheet">
<link href="{% static 'dashboard/css/plugins/select2/select2.min.css' %}" rel="stylesheet">
<link href="{% static 'dashboard/css/plugins/select2/select2-bootstrap4.min.css' %}" rel="stylesheet">
{% endblock extracss%}
{% block content %}
<div id="page-wrapper" class="gray-bg">
    {% include 'destinations/navbar_top.html' %}
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-3">
                {% include 'dashboard/mailbox/mailbox_menu_left.html' %}
            </div>
            <div class="col-lg-9 animated fadeInRight">
                <div class="mail-box-header">
                    <h2>
                        {% trans "Compose message" %}
                    </h2>
                </div>
                <div class="mail-box">
                    <form method="POST"  enctype="multipart/form-data">{% csrf_token %}
                        {% if user.groups.all.0.name == "Manager" %}
                        <div class="mail-body">
                            <label class="col-form-label"><b>{% trans "Select an user" %}:</b></label>
                            <select class="select2_demo_2 form-control" name="recipient" multiple="multiple" placeholder="{% trans 'Select an user' %}">
                                {% for usuarios in usuarios %}
                                <option value="{{ usuarios.pk }}">{{usuarios.email}}</option>
                                {% endfor %}
                            </select>
                        </div>
                        {% endif %}

                        <div class="mail-body">
                                <div class="form-group row">
                                    <label class="col-sm-2 col-form-label"><b>{% trans "Subject" %}:</b></label>
                                    <div class="col-sm-10"><input type="text" name="subject" class="form-control" value="" required></div>
                                </div>
                        </div>
                        <div class="mail-text h-200">
                            <div class="form-group ">
                                <label class="col-sm-2 col-form-label"><b>{% trans "Message" %}:</b></label>
                                <textarea id="summernote" name="message">
                                
                                </textarea>
                            </div>
                            <div class="clearfix"></div>
                        </div>

                        <div class="mail-body">
                                <div class="form-group row">
                                    <label><b>{% trans "Attach file"%}</b></label>
                                    <div class="custom-file">        
                                        <input type="file" name="attach">
                                    </div> 
                                </div>
                        </div>
                        <div class="mail-body text-right tooltip-demo">
                            <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-reply"></i> {% trans "Send" %}</button>
                            <a href="{% url 'dashboard:mailbox' %}" class="btn btn-danger btn-sm"><i class="fa fa-times"></i> {% trans "Discard" %}</a>
                        </div>
                        <div class="clearfix"></div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% include 'destinations/footer.html' %}
</div>
{% endblock content %}
{% block extrajs%}
<!-- SUMMERNOTE -->
<script src="{% static 'dashboard/extras/summernote/summernote.min.js' %}"></script>
<script src="{% static 'dashboard/js/plugins/select2/select2.full.min.js' %}"></script>
<script>

    $(document).ready(function () {
        $(".select2_demo_2").select2({
            theme: 'bootstrap4',
        });

        
        $('#summernote').summernote({
            height: 200,
            tooltip: false,
            focus: true,
        });
    });
</script>
{% endblock extrajs %}

travel/apps/destinations/templates/dashboard/mailbox/_mailboxmain.html
{% extends 'destinations/base.html' %}
{% load static i18n destinations_tags static %}
{% block title %}{% trans 'Mailbox - Travelposting' %}{% endblock %}
{% block extracss %}
<!-- FooTable -->
<link href="{% static 'dashboard/css/plugins/footable/footable.core.css' %}" rel="stylesheet">
<link href="{% static 'dashboard/css/plugins/iCheck/custom.css' %}" rel="stylesheet">
{% endblock extracss%}
{% block content %}
<div id="page-wrapper" class="gray-bg">
    {% include 'destinations/navbar_top.html' %}
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-3">
                {% include 'dashboard/mailbox/mailbox_menu_left.html' %}
            </div>
            <div class="col-lg-9 animated fadeInRight">
                <div class="mail-box-header">
                    <h2>
                        {% trans 'Inbox' %}({{ conteo }})
                    </h2>
                </div>
                {% include "dashboard/mailbox/tablemain.html" %}
            </div>
        </div>
    </div>
    {% include 'destinations/footer.html' %}
</div>
{% endblock content %}
{% block js %}
{{ block.super }}
{{ form.media.js }}
<!-- FooTable -->
<script src="{% static 'dashboard/js/plugins/footable/footable.all.min.js' %}"></script>
<!-- iCheck -->
<script src="{% static 'dashboard/js/plugins/iCheck/icheck.min.js' %}"></script>
<script>
    //Delete fuction
    function delete_mail(pk_i){
          swal({
              title: "{% trans 'Are you sure?' %}",
              text: "{% trans 'If you delete this message you will not be able to recover it' %}",
              type: "warning",
              showCancelButton: true,
              confirmButtonColor: "#DD6B55",
              confirmButtonText: "{% trans 'Yes, delete it!' %}",
              closeOnConfirm: false
          }, function () {
            $.ajax({
                  method:'DELETE',
                  url:'{% url 'destinations:delete-mail' %}',
                  data:{
                    pk:pk_i,
                  },
                  beforeSend: function(xhr) {
                      xhr.setRequestHeader("X-CSRFToken", '{{ csrf_token }}');
                  },
                  success: function (request) {
                  if(request.status==true){
                    swal("{% trans 'Deleted!' %}", "{% trans 'Message has been deleted.' %}", "success");
                    setTimeout(function(){
                        window.location.href = "{% url 'destinations:mailbox' %}";
                    }, 2000);
                  }else{
                      swal("{% trans 'Error!' %}", "{% trans 'Has been not deleted' %}", "error");
                  }
                  }
              });
          });
    }

    /* End fuction */
    
    
    $(document).ready(function () {
     $('.i-checks').iCheck({
         checkboxClass: 'icheckbox_square-green',
             radioClass: 'iradio_square-green',
     });
    });
    
    
    $(document).ready(function () {
     $('.footable').footable();
     $('.footable2').footable();
    });
</script>
{% endblock js %}

travel/apps/destinations/templates/dashboard/mailbox/mailbox_menu_left.html
{% load static i18n destinations_tags static %}

<div class="ibox ">
    <div class="ibox-content mailbox-content">
        <div class="file-manager">
            <a class="btn btn-block btn-primary compose-mail" href="{% url 'dashboard:mailbox-add' %}">
                {% trans "New Message" %}
            </a>
            <div class="space-25"></div>
                <h5>{% trans "Folders" %}</h5>
                <ul class="folder-list m-b-md" style="padding: 0">
                    <li>
                        <a href="{% url 'dashboard:mailbox' %}">
                            <i class="fa fa-inbox "></i> 
                            {% trans "Inbox" %}
                            {% if conteo >= 1 %}
                            <span class="label label-warning float-right">
                            
                            {{ conteo }}</span>
                            {% endif %} 
                        </a>
                    </li>
                    <li>
                        <a href="{% url 'dashboard:mailbox-sent' %}"> <i class="fa fa-envelope-o"></i>
                            {% trans "Messages sent" %}
                        </a>
                    </li>
                </ul>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>