travel/apps/accounts/urls.py
from django.urls import path
from apps.accounts import views
from django.contrib.auth.views import logout_then_login


app_name = 'accounts'

urlpatterns = [
    path(
        'activate/complete/',
        views.isuccess,
         name='activate-complete',
    ),

    path(
        'activate/<str:activation_key>/',
        views.ActivateAccountView.as_view(),
        name='activate',
    ),

    path(
        'register/',
        views.RegisterView.as_view(),
        name='register',
    ),

    path('register/<valor>/<int>', views.RegisterView.as_view(), name='register2'),

    path(
        'login/',
        views.LoginView.as_view(),
        name='login',
    ),

    path(
        'logout/',
        logout_then_login,
        name='logout',
    ),

    path(
        'register/success/',
        views.isuccess,
        name='register-complete',
    ),

    path(
        'password_reset/',
        views.PasswordResetView.as_view(),
        name='password-reset',
    ),

    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password-reset-confirm',
    ),

    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(),
        name='password-reset-done',
    ),

    path(
        'reset/complete/',
        views.PasswordResetCompleteView.as_view(),
        name='password-reset-complete',
    ),

    path(
        'password_change/',
        views.PasswordChangeView.as_view(),
        name='password-change',
    ),

    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(),
        name='password-change-done',
    ),

    path(
        'user/<int:pk>/details/',
        views.CustomUserDetailView.as_view(),
        name='user-details',
    ),

    path(
        'user/<int:pk>/update/',
        views.CustomUserUpdateView.as_view(),
        name='user-update',
    ),

    path(
        'user/<int:pk>/complete/',
        views.CompleteProfileView.as_view(),
        name='user-complete-profile',
    ),
    path(
        'user/<int:pk>/update/',
        views.CustomUserUpdateView.as_view(),
        name='user-update',
    ),
]

travel/apps/destinations/urls.py
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import path

from apps.accounts.models import CustomerUser
from apps.destinations.charts import (
    BookingCharts,
    DashboardIndex,
    DestinationCharts,

)
from apps.destinations.views.visitor import (
    VisitorView,
)

from apps.destinations.views.destination import (
    AgencyAddView,
    AgencyDeleteView,
    AgencyAddExistingUserView,
    AgencyUpdateView,
    AgencyView,
    DestinationListView,
    DestinationCreateView,
    DestinationDetailView,
    DestinationUpdateView,
    DestinationDeleteView,
    GalleryListView,
    VideoListView,
    OptionTabDataTemplateAjaxView,
    ItineraryCreateView,
    ItineraryUpdateView,
    ItineraryView,
    RequestDeleteView,
    RequestManagerView,
    RequestProcessView,
    RequestView,
    SocialNetworkListView,
    SocialNetworkUpdateView,
    MailboxView,
    MailboxAdd,
    MailboxReply,
    MailboxDetail,
    MailboxSent,
    messageView,
    LeaderView,
    LeaderAddView,
    LeaderAddExistingUserView,
    LeaderDeleteView,
    DocumentView,
    DocumentAdd,
    DocumentUpdateView,
    FileDocumentsView,
    SearchDocumentsView
)

from apps.destinations.views.booking import (
    BookingListView,
    BookingSaveStat,
    UpdateBooking
)

from apps.destinations.views.maps import (
    DestinationMapView,
    MapListView,
)


def nocommunity_access(function=None, redirect_field_name=REDIRECT_FIELD_NAME, login_url=None):
    actual_decorator = user_passes_test(
        lambda u: u.is_authenticated,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    nocom_decorator = user_passes_test(
        lambda u: u.is_authenticated and not u.is_community,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    if function:
        return actual_decorator(function) and  nocom_decorator(function)
    return actual_decorator and nocom_decorator



app_name = 'destinations'
urlpatterns = [
    path(
        '',
        nocommunity_access(DashboardIndex),
        name='dashboard-index',
    ),
    path(
        'documents',
        nocommunity_access(DocumentView.as_view()),
        name='documents',
    ),
    path('documents/add/',
        nocommunity_access(DocumentAdd.as_view()),
        name='documents-add'
    ),
    path(
        'documents/delete',
        nocommunity_access(DocumentView.as_view()),
        name='documents-delete',
    ),
    path(
        'documents/<int:pk>/update/',
        nocommunity_access(DocumentUpdateView.as_view()),
        name='documents-update',
    ),
    path(
        'files/',
        nocommunity_access(FileDocumentsView.as_view()),
        name='files-documents',
    ),
    path(
        'files/search',
        nocommunity_access(SearchDocumentsView.as_view()),
        name='files-search',
    ),
    path(
        'managers',
        nocommunity_access(LeaderView.as_view()),
        name='manager',
    ),
    path(
        'managers/add/existing',
        nocommunity_access(LeaderAddExistingUserView.as_view()),
        name='manager-add-existing'
    ),
    path(
        'managers/add/',
        nocommunity_access(LeaderAddView.as_view()),
        name='manager-add',
    ),
    path(
        'managers/<int:pk>/delete',
        nocommunity_access(LeaderDeleteView.as_view()),
        name='manager-delete'
    ),
    path(
        'agencies/list',
        nocommunity_access(AgencyView.as_view()),
        name='agencies',
    ),
    path(
        'agencies/add/existing',
        nocommunity_access(AgencyAddExistingUserView.as_view()),
        name='agency-add-existing'
    ),
    path(
        'agencies/add',
        nocommunity_access(AgencyAddView.as_view()),
        name='agency-add'
    ),
    path(
        'agencies/<int:pk>/delete',
        nocommunity_access(AgencyDeleteView.as_view()),
        name='agency-delete'
    ),

    path(
        'agencies/<int:pk>/',
        nocommunity_access(AgencyUpdateView.as_view()),
        name='agency-edit'
    ),
    path(
        'mailbox',
        nocommunity_access(MailboxView.as_view()),
        name='mailbox',
    ),
    path(
        'mailbox/sent',
        nocommunity_access(MailboxSent.as_view()),
        name='mailbox-sent',
    ),
    path(
        'mailbox/delete-mail',
        nocommunity_access(MailboxView.as_view()),
        name='delete-mail',
    ),
    path(
        'mailbox/add',
        nocommunity_access(MailboxAdd.as_view()),
        name='mailbox-add',
    ),
    path(
        'mailbox/reply/<int>',
        nocommunity_access(MailboxReply.as_view()),
        name='mailbox-reply',
    ),
    path(
        'mailbox/<int>',
        nocommunity_access(MailboxDetail.as_view()),
        name='mailbox-detail'
    ),

    path(
        'list',
        nocommunity_access(DestinationListView.as_view()),
        name='list',
    ),

    path(
        'create/',
        nocommunity_access(DestinationCreateView.as_view()),
        name='create',
    ),

    path(
        '<int:pk>/create/',
        nocommunity_access(DestinationDetailView.as_view()),
        name='detail',
    ),

    path(
        '<int:pk>/update/',
        nocommunity_access(DestinationUpdateView.as_view()),
        name='update',
    ),

    path(
        '<int:pk>/delete/',
        nocommunity_access(DestinationDeleteView.as_view()),
        name='delete',
    ),

    path(
        'social-network/',
        nocommunity_access(SocialNetworkListView.as_view()),
        name='social-network',
    ),
    path(
        'social-network/delete-setting',
        nocommunity_access(SocialNetworkListView.as_view()),
        name='delete-setting',
    ),
    path(
        '<int:pk>/up/',
        nocommunity_access(SocialNetworkUpdateView.as_view()),
        name='update-social',
    ),

    path(
        '<int:pk>/gallery/',
        nocommunity_access(GalleryListView.as_view()),
        name='gallery-list',
    ),

    path(
        '<int:pk>/video/',
        nocommunity_access(VideoListView.as_view()),
        name='video-list',
    ),

    path(
        'option/<int:pk>/template/',
        nocommunity_access(OptionTabDataTemplateAjaxView.as_view()),
        name='option-template',
    ),

    path(
        'itinerary/get-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='get-itinerary',
    ),

    path(
        'itinerary/add-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='add-itinerary',
    ),
    path(
        'itinerary/update-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='update-itinerary',
    ),
    path(
        'itinerary/delete-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='delete-itinerary',
    ),
    path(
        'itinerary/create/',
        nocommunity_access(ItineraryCreateView.as_view()),
        name='itinerary-create',
    ),
    path(
        'itinerary/<pk>/edit/',
        nocommunity_access(ItineraryUpdateView.as_view()),
        name='itinerary-edit',
    ),

    path(
        'itinerary/',
        nocommunity_access(ItineraryView.as_view()),
        name='itinerary-list',
    ),

    path(
        'booking-list/',
        nocommunity_access(BookingListView.as_view()),
        name='booking-list',
    ),

    path(
        'booking-charts/',
        nocommunity_access(BookingCharts),
        name='booking-charts',
    ),

    path(
        'booking-save/',
        nocommunity_access(BookingSaveStat.as_view()),
        name='booking-save',
    ),

    path(
        'update-booking/',
        nocommunity_access(UpdateBooking.as_view()),
        name='update-booking',
    ),

    path(
        'destination-charts/',
        nocommunity_access(DestinationCharts),
        name='destination-charts',
    ),

    path(
        'maps/get-list',
        nocommunity_access(MapListView.as_view()),
        name='list-maps',
    ),

    path(
        'maps/add-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='add-map',
    ),
    path(
        'maps/update-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='update-map',
    ),
    path(
        'maps/delete-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='delete-map',
    ),


    path(
        'maps/',
        nocommunity_access(DestinationMapView.as_view()),
        name='destination-map',
    ),

    path(
        'message/',
        nocommunity_access(messageView.as_view()),
        name='send_message',
    ),

    path(
        'requests/manager',
        nocommunity_access(RequestManagerView.as_view()),
        name='requests_manager',
    ),
    path(
        'requests/<int:pk>/approve/',
        nocommunity_access(RequestProcessView.as_view(action='approve')),
        name='requests_approve',
    ),

    path(
        'requests/<int:pk>/reject/',
        nocommunity_access(RequestProcessView.as_view(action='reject')),
        name='requests_reject',
    ),

    path(
        'requests/<int:pk>/delete/',
        nocommunity_access(RequestDeleteView.as_view()),
        name='requests_delete',
    ),

    path(
        'requests/',
        nocommunity_access(RequestView.as_view()),
        name='requests',
    ),

    path(
        'visitor/',
        nocommunity_access(VisitorView.as_view()),
        name='visitor',
    ),
]

travel/apps/payments/paypal/urls.py
from django.urls import path

from apps.payments.paypal.views import CancelRedirectView, ApproveRedirectView

app_name = 'paypal'
urlpatterns = [
    path(
        'subscription/approved',
        ApproveRedirectView.as_view(),
        name='subscription-approved',
    ),

    path(
        'subscription/cancel',
        CancelRedirectView.as_view(),
        name='subscription-cancel',
    ),

]

travel/config/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django_js_reverse import views
from apps.landing_page.views import (
    CategoriesView,
    DetailDestinationView,
    SaveSearchView,
    DeleteRegisterView,
    PrivacySettingView,
    getItineraryPDF,
    ContactUs,
)

from apps.destinations.views.booking import BookingSaveView
from django.contrib.auth.decorators import login_required
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500
)


#import notifications.urls

admin.autodiscover()

urlpatterns = [
    url(
        r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}},
    ),

    url(
        r'^rosetta/',
        include('rosetta.urls'),
    ),

    path(
        'api/',
        include('apps.api.urls', namespace='api'),
    ),

    path(
        'ratings/',
        include('star_ratings.urls', namespace='ratings')
    ),

    url(
        r'^jsreverse/$',
        views.urls_js, name='js_reverse'
    ),
]

urlpatterns += i18n_patterns(
    url(
        r'^nested_admin/',
        include('nested_admin.urls'),
    ),

    url(
        r'^admin/',
        admin.site.urls,
    ),

    url(
        r'^impersonate/',
        include('impersonate.urls'),
    ),

    path(
        'summernote/',
        include('django_summernote.urls'),
    ),

    url(
        r'^accounts/',
        include("apps.accounts.urls", namespace='accounts'),
    ),

    path(
        'directmessages/',
        include("apps.directmessages.urls")
    ),

    url(
        r'^category/destination/(?P<slug>\w+)',
        DetailDestinationView.as_view(),
        name='view_detail_destination',
    ),

    url(
        r'^search/',
        CategoriesView.as_view(),
        name='search_category',
    ),

    url(
        r'^category/(?P<alias>\w+)',
        CategoriesView.as_view(),
        name='view_category',
    ),

    path(
        'community/',
        include('apps.community.urls'),
        name='community',
    ),

    path(
        'paypal/',
        include('apps.payments.paypal.urls'),
    ),

    path(
        'dashboard/',
        include("apps.destinations.urls",
                namespace='dashboard'),
    ),

    path(
        'advertisements/',
        include("apps.advertisements.urls",
                namespace='advertisements'),
    ),

    path(
        'personal-search/',
        SaveSearchView.as_view(),
        name='personal-search',
    ),

    path(
        'make-booking/',
        BookingSaveView.as_view(),
        name='make-booking',
    ),

    path(
        'delete-register/',
        DeleteRegisterView.as_view(),
        name='delete-register',
    ),

    path(
        'setting-privacy/',
        PrivacySettingView.as_view(),
        name='setting-privacy',
    ),

    url(r'^get-itinerary/(?P<slug>\w+)',
        getItineraryPDF.as_view(),
        name='get_itinerary'),

    url(r'contact-us',
        ContactUs.as_view(),
        name='contact-us'),

    url(
        r'^',
        include('cms.urls'),
        name='index',
    ),

    #url('^inbox/notifications/',
    #    include(notifications.urls, namespace='notifications')),


)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom Defaults Pages https://docs.djangoproject.com/en/2.1/ref/views/#error-views
handler400 = 'apps.landing_page.views.pag_400_bad_request'
handler403 = 'apps.landing_page.views.pag_403_permission_denied'
handler404 = 'apps.landing_page.views.pag_404_page_not_found'
handler500 = 'apps.landing_page.views.pag_500_server_error'

travel/apps/destinations/views/visitor.py
from django.contrib.gis.geoip2 import GeoIP2
from django.conf import settings
from django.http import JsonResponse
from django.views.generic import (
    View,
)
from django.utils.translation import gettext_lazy as _

from apps.destinations.models import (
	Destination,
	DestinationVisitor
)
from apps.destinations.utils import get_client_ip

class VisitorView(View):
    def get(self, request):
    	geo_ip = GeoIP2()
    	if settings.DEBUG :
    		ip_visitor = "72.14.207.99"
    		data_visitor = geo_ip.city(ip_visitor)
    	else:
    		ip_visitor = get_client_ip(request)
    		data_visitor = geo_ip.city(str(ip_visitor))
    	try:
	    	DestinationVisitor.objects.create(
	    		destination = Destination.objects.get(pk=request.GET['destination']),
	    		ip_address  = ip_visitor,
	    		dma_code =data_visitor['dma_code'] ,
	    		country_code = data_visitor['country_code'],
	    		country_name =data_visitor['country_name']
	    	)
	    	return JsonResponse({},safe=False,status=200)
    	except Exception as e:
    		return JsonResponse({},safe=False,status=500)

travel/apps/destinations/templates/destinations/_delete.html
{% load i18n %}

<form method="post"
      action="{% url 'destinations:delete' object.pk %}">{% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal"><span
        aria-hidden="true">×</span><span class="sr-only">{% trans 'Close' %}</span></button>
    <h4 class="modal-title">{{ object }}</h4>
    <!-- <small class="font-bold">Delete this contract</small> -->
  </div>
  <div class="modal-body">
    <p>
      {% blocktrans %}
        Are you sure you want to delete the destination {{ object }}?
      {% endblocktrans %}
    </p>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-danger">{% trans 'Delete' %}</button>
    <button type="button" class="btn btn-white" data-dismiss="modal">{% trans 'Close' %}</button>
  </div>
</form>

travel/apps/destinations/templates/destinations/footer.html
{% load i18n %}

<div class="footer">
  <div class="float-right">
    <strong>{% trans "Travelposting" %}</strong>.
  </div>
  <div>
    <strong>© Travelposting » 2020 </strong> « {% trans "All Rights Reserved Site Map Disclaimer." %}
  </div>
</div>

travel/apps/destinations/templates/destinations/navbar_left.html
{% load i18n %}

<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu" style="">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    {% if request.user.avatar %}
                    <img alt="image" class="rounded-circle" src="{{ request.user.avatar.url }}" height="48" width="48">
                    {% else %}
                    <i class="fa fa-user fa-3x" style="color: white;"></i>
                    {% endif %}
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                    <span class="block m-t-xs font-bold">{{ user.get_full_name }}</span>
                    <span class="text-muted text-xs block">
                      {% if request.user.is_staff %}
                      {% trans 'Admin' %}
                      {% else %}
                      {% trans 'Company' %}
                      {% endif %}
                      <b class="caret"></b></span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                      <li>
                        <a href="{% url 'accounts:user-details' request.user.pk %}"
                           title="{% trans 'Information' %}">{% trans 'Information' %}</a>
                      </li>
                      <li>
                        <a href="{% url 'accounts:password-change' %}"
                           title="{% trans 'Change password' %}">{% trans 'Change password' %}</a>
                      </li>
                      <li>
                        <a href="{% url 'accounts:logout' %}"
                           title="{% trans 'Close session' %}">{% trans 'Close session' %}</a>
                      </li>
                    </ul>
                </div>
                <div class="logo-element">
                    T&S
                </div>
            </li>
            {% if request.get_full_path == '/es/dashboard/' or request.get_full_path == '/en/dashboard/' or request.get_full_path == '/de/dashboard/' %}
            <li class="special_link">
            {% else %}
            <li>
            {% endif %}
              <a href="{% url 'dashboard:dashboard-index' %}" title="{% trans 'Home' %}">
                <i class="fa fa-th-large"></i> <span class="nav-label">{% trans 'Home' %}</span>
              </a>
            </li>
              {% if request.get_full_path == '/es/dashboard/mailbox' or request.get_full_path == '/en/dashboard/mailbox' or request.get_full_path == '/de/dashboard/mailbox' %}

                <li class="special_link">
              {% else %}
                <li>
              {% endif %}
                  <a href="{% url 'dashboard:mailbox' %}" title="{% trans 'Mailbox' %}">
                    <i class="fa fa-envelope-o fa-lg"></i>
                    <span class="nav-label">{% trans 'Mailbox' %}</span>
                  </a>
                </li>
            {% if request.user.is_staff %}
            <li class="">
              <a href="/rosetta/" title="{% trans 'Translate site' %}">
                <i class="fa fa-language fa-lg"></i>
                <span class="nav-label">{% trans 'Translate site' %}</span>
              </a>
            </li>
            <li class="">
              <a href="/admin/" title="{% trans 'Admin site' %}">
                <i class="fa fa-user-secret fa-lg"></i>
                <span class="nav-label">{% trans 'Admin site' %}</span>
              </a>
            </li>
            <li class="">
              <a href="#">
                <i class="fa fa-user fa-lg"></i>
                <span class="nav-label">{% trans "Managers" %}</span>
                <span class="fa arrow"></span>
              </a>
              <ul class="nav nav-second-level">
                <li class=""><a href="{% url 'dashboard:documents'%}" title="{% trans 'Documents' %}"><i class="fa fa-file-pdf-o"></i>{% trans 'Documents' %}</a></li>
                <li class=""><a href="{% url 'dashboard:requests_manager' %}" title="{% trans 'Pending Requests' %}">{% trans 'Pending Requests' %}</a></li>
                <li class=""><a href="{% url 'dashboard:manager' %}" title="{% trans 'List Managers' %}">{% trans 'List Managers' %}</a></li>
                <li class=""><a href="{% url 'dashboard:manager' %}" title="{% trans 'Add Manager' %}">{% trans 'Add Manager' %}</a></li>
                <li class=""><a href="{% url 'dashboard:agencies' %}" title="{% trans 'Agencies List' %}">{% trans 'Agencies List' %}</a></li>
                <li class=""><a href="{% url 'dashboard:agency-add' %}" title="{% trans 'Add agency' %}">{% trans 'Add agency' %}</a></li>
              </ul>
            </li>
            {% endif %}
            <li class="">
              <a href="#">
                <i class="fa fa-globe fa-lg"></i>
                <span class="nav-label">{% trans 'Destinations' %}</span>
                <span class="fa arrow"></span>
              </a>
              <ul class="nav nav-second-level">
                <li class="">
                  <a href="{% url 'dashboard:list' %}" title="{% trans 'Your destinations' %}">{% trans 'Your destinations' %}</a>
                </li>
                <li class="">
                  <a href="{% url 'dashboard:itinerary-list' %}" title="{% trans 'Itinerary' %}">{% trans 'Itinerary' %}</a>
                </li>
                <li class="">
                  <a href="{% url 'dashboard:destination-map' %}" title="{% trans 'Maps' %}">{% trans 'Maps' %}</a>
                </li>
                <li class="">
                  <a href="{% url 'dashboard:social-network' %}" title="{% trans 'Social Network' %}">{% trans 'Social Network' %}</a>
                </li>
              </ul>
            </li>
            <li class="">
              <a href="#">
                <i class="fa fa-buysellads fa-lg"></i>
                <span class="nav-label">{% trans 'Ads' %}</span>
                <span class="fa arrow"></span>
              </a>
              <ul class="nav nav-second-level collapse" aria-expanded="false">
                <li class="">
                  <a href="{% url 'advertisements:advertisers-list' %}" title="{% trans 'Ad Advertisers' %}">
                    <i class="fa fa-users fa-lg"></i>{% trans 'Ad Advertisers' %}
                  </a>
                </li>
                <li class="">
                  <a href="{% url 'advertisements:categories-list' %}" title="{% trans 'Ad Categories' %}">
                    <i class="fa fa-folder fa-lg"></i>{% trans 'Ad Categories' %}
                  </a>
                </li>
                <li class="">
                  <a href="{% url 'advertisements:ads-list' %}" title="{% trans 'Advertisements' %}">
                    <i class="fa fa-cog fa-lg"></i>{% trans 'Advertisements' %}
                  </a>
                </li>
                <li class="">
                  <a href="{% url 'advertisements:ad-images-list' %}" title="{% trans 'Your Ad Images' %}">
                    <i class="fa fa-image fa-lg"></i>{% trans 'Your Ad Images' %}
                  </a>
                </li>
              </ul>
            </li>
            <li class="">
              <a href="#">
                <i class="fa fa-book fa-lg"></i>
                <span class="nav-label">{% trans 'Reservations' %}</span>
                <span class="fa arrow"></span>
              </a>
              <ul class="nav nav-second-level">
                <li class="">
                  <a href="{% url 'dashboard:booking-list' %}" title="{% trans 'Your reservations' %}">{% trans 'Your reservations' %}</a></li>
              </ul>
            </li>
            {% if not request.user.is_superuser %}
            <li class="">
              {% if not perms.accounts.manager_country and not perms.accounts.manager  %}
                <a href="{% url 'destinations:requests' %}" title="{% trans 'Requests' %}">
              {% else %}
                <a href="{% url 'destinations:requests_manager' %}" title="{% trans 'Requests' %}">
              {% endif %}
                <i class="fa fa-book fa-lg"></i>
                <span class="nav-label">{% trans 'Requests' %}</span>
              </a>
            </li>
            {% endif %}
            {% if not request.user.is_staff %}
            <li class="">
                <a href="{% url 'dashboard:files-documents' %}" title="{% trans 'Documents' %}">
                <i class="fa fa-file-pdf-o"></i>
                <span class="nav-label">{% trans 'Documents' %}</span>
              </a>
            </li>
            {% endif %}

        </ul>
    </div>
</nav>