travel/apps/destinations/urls.py
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import path

from apps.accounts.models import CustomerUser
from apps.destinations.charts import (
    BookingCharts,
    DashboardIndex,
    DestinationCharts,

)
from apps.destinations.views.visitor import (
    VisitorView,
)

from apps.destinations.views.destination import (
    AgencyAddView,
    AgencyDeleteView,
    AgencyAddExistingUserView,
    AgencyUpdateView,
    AgencyView,
    DestinationListView,
    DestinationCreateView,
    DestinationDetailView,
    DestinationUpdateView,
    DestinationDeleteView,
    GalleryListView,
    VideoListView,
    OptionTabDataTemplateAjaxView,
    ItineraryCreateView,
    ItineraryUpdateView,
    ItineraryView,
    RequestDeleteView,
    RequestManagerView,
    RequestProcessView,
    RequestView,
    SocialNetworkListView,
    SocialNetworkUpdateView,
    MailboxView,
    MailboxAdd,
    MailboxReply,
    MailboxDetail,
    MailboxSent,
    messageView,
    LeaderView,
    LeaderAddView,
    LeaderAddExistingUserView,
    LeaderDeleteView,
    DocumentView,
    DocumentAdd,
    DocumentUpdateView,
    FileDocumentsView,
    SearchDocumentsView
)

from apps.destinations.views.booking import (
    BookingListView,
    BookingSaveStat,
    UpdateBooking
)

from apps.destinations.views.maps import (
    DestinationMapView,
    MapListView,
)


def nocommunity_access(function=None, redirect_field_name=REDIRECT_FIELD_NAME, login_url=None):
    actual_decorator = user_passes_test(
        lambda u: u.is_authenticated,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    nocom_decorator = user_passes_test(
        lambda u: u.is_authenticated and not u.is_community,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    if function:
        return actual_decorator(function) and  nocom_decorator(function)
    return actual_decorator and nocom_decorator



app_name = 'destinations'
urlpatterns = [
    path(
        '',
        nocommunity_access(DashboardIndex),
        name='dashboard-index',
    ),
    path(
        'documents',
        nocommunity_access(DocumentView.as_view()),
        name='documents',
    ),
    path('documents/add/',
        nocommunity_access(DocumentAdd.as_view()),
        name='documents-add'
    ),
    path(
        'documents/delete',
        nocommunity_access(DocumentView.as_view()),
        name='documents-delete',
    ),
    path(
        'documents/<int:pk>/update/',
        nocommunity_access(DocumentUpdateView.as_view()),
        name='documents-update',
    ),
    path(
        'files/',
        nocommunity_access(FileDocumentsView.as_view()),
        name='files-documents',
    ),
    path(
        'files/search',
        nocommunity_access(SearchDocumentsView.as_view()),
        name='files-search',
    ),
    path(
        'managers',
        nocommunity_access(LeaderView.as_view()),
        name='manager',
    ),
    path(
        'managers/add/existing',
        nocommunity_access(LeaderAddExistingUserView.as_view()),
        name='manager-add-existing'
    ),
    path(
        'managers/add/',
        nocommunity_access(LeaderAddView.as_view()),
        name='manager-add',
    ),
    path(
        'managers/<int:pk>/delete',
        nocommunity_access(LeaderDeleteView.as_view()),
        name='manager-delete'
    ),
    path(
        'agencies/list',
        nocommunity_access(AgencyView.as_view()),
        name='agencies',
    ),
    path(
        'agencies/add/existing',
        nocommunity_access(AgencyAddExistingUserView.as_view()),
        name='agency-add-existing'
    ),
    path(
        'agencies/add',
        nocommunity_access(AgencyAddView.as_view()),
        name='agency-add'
    ),
    path(
        'agencies/<int:pk>/delete',
        nocommunity_access(AgencyDeleteView.as_view()),
        name='agency-delete'
    ),

    path(
        'agencies/<int:pk>/',
        nocommunity_access(AgencyUpdateView.as_view()),
        name='agency-edit'
    ),
    path(
        'mailbox',
        nocommunity_access(MailboxView.as_view()),
        name='mailbox',
    ),
    path(
        'mailbox/sent',
        nocommunity_access(MailboxSent.as_view()),
        name='mailbox-sent',
    ),
    path(
        'mailbox/delete-mail',
        nocommunity_access(MailboxView.as_view()),
        name='delete-mail',
    ),
    path(
        'mailbox/add',
        nocommunity_access(MailboxAdd.as_view()),
        name='mailbox-add',
    ),
    path(
        'mailbox/reply/<int>',
        nocommunity_access(MailboxReply.as_view()),
        name='mailbox-reply',
    ),
    path(
        'mailbox/<int>',
        nocommunity_access(MailboxDetail.as_view()),
        name='mailbox-detail'
    ),

    path(
        'list',
        nocommunity_access(DestinationListView.as_view()),
        name='list',
    ),

    path(
        'create/',
        nocommunity_access(DestinationCreateView.as_view()),
        name='create',
    ),

    path(
        '<int:pk>/create/',
        nocommunity_access(DestinationDetailView.as_view()),
        name='detail',
    ),

    path(
        '<int:pk>/update/',
        nocommunity_access(DestinationUpdateView.as_view()),
        name='update',
    ),

    path(
        '<int:pk>/delete/',
        nocommunity_access(DestinationDeleteView.as_view()),
        name='delete',
    ),

    path(
        'social-network/',
        nocommunity_access(SocialNetworkListView.as_view()),
        name='social-network',
    ),
    path(
        'social-network/delete-setting',
        nocommunity_access(SocialNetworkListView.as_view()),
        name='delete-setting',
    ),
    path(
        '<int:pk>/up/',
        nocommunity_access(SocialNetworkUpdateView.as_view()),
        name='update-social',
    ),

    path(
        '<int:pk>/gallery/',
        nocommunity_access(GalleryListView.as_view()),
        name='gallery-list',
    ),

    path(
        '<int:pk>/video/',
        nocommunity_access(VideoListView.as_view()),
        name='video-list',
    ),

    path(
        'option/<int:pk>/template/',
        nocommunity_access(OptionTabDataTemplateAjaxView.as_view()),
        name='option-template',
    ),

    path(
        'itinerary/get-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='get-itinerary',
    ),

    path(
        'itinerary/add-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='add-itinerary',
    ),
    path(
        'itinerary/update-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='update-itinerary',
    ),
    path(
        'itinerary/delete-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='delete-itinerary',
    ),
    path(
        'itinerary/create/',
        nocommunity_access(ItineraryCreateView.as_view()),
        name='itinerary-create',
    ),
    path(
        'itinerary/<pk>/edit/',
        nocommunity_access(ItineraryUpdateView.as_view()),
        name='itinerary-edit',
    ),

    path(
        'itinerary/',
        nocommunity_access(ItineraryView.as_view()),
        name='itinerary-list',
    ),

    path(
        'booking-list/',
        nocommunity_access(BookingListView.as_view()),
        name='booking-list',
    ),

    path(
        'booking-charts/',
        nocommunity_access(BookingCharts),
        name='booking-charts',
    ),

    path(
        'booking-save/',
        nocommunity_access(BookingSaveStat.as_view()),
        name='booking-save',
    ),

    path(
        'update-booking/',
        nocommunity_access(UpdateBooking.as_view()),
        name='update-booking',
    ),

    path(
        'destination-charts/',
        nocommunity_access(DestinationCharts),
        name='destination-charts',
    ),

    path(
        'maps/get-list',
        nocommunity_access(MapListView.as_view()),
        name='list-maps',
    ),

    path(
        'maps/add-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='add-map',
    ),
    path(
        'maps/update-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='update-map',
    ),
    path(
        'maps/delete-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='delete-map',
    ),


    path(
        'maps/',
        nocommunity_access(DestinationMapView.as_view()),
        name='destination-map',
    ),

    path(
        'message/',
        nocommunity_access(messageView.as_view()),
        name='send_message',
    ),

    path(
        'requests/manager',
        nocommunity_access(RequestManagerView.as_view()),
        name='requests_manager',
    ),
    path(
        'requests/<int:pk>/approve/',
        nocommunity_access(RequestProcessView.as_view(action='approve')),
        name='requests_approve',
    ),

    path(
        'requests/<int:pk>/reject/',
        nocommunity_access(RequestProcessView.as_view(action='reject')),
        name='requests_reject',
    ),

    path(
        'requests/<int:pk>/delete/',
        nocommunity_access(RequestDeleteView.as_view()),
        name='requests_delete',
    ),

    path(
        'requests/',
        nocommunity_access(RequestView.as_view()),
        name='requests',
    ),

    path(
        'visitor/',
        nocommunity_access(VisitorView.as_view()),
        name='visitor',
    ),
]

travel/apps/payments/paypal/urls.py
from django.urls import path

from apps.payments.paypal.views import CancelRedirectView, ApproveRedirectView

app_name = 'paypal'
urlpatterns = [
    path(
        'subscription/approved',
        ApproveRedirectView.as_view(),
        name='subscription-approved',
    ),

    path(
        'subscription/cancel',
        CancelRedirectView.as_view(),
        name='subscription-cancel',
    ),

]

travel/config/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django_js_reverse import views
from apps.landing_page.views import (
    CategoriesView,
    DetailDestinationView,
    SaveSearchView,
    DeleteRegisterView,
    PrivacySettingView,
    getItineraryPDF,
    ContactUs,
)

from apps.destinations.views.booking import BookingSaveView
from django.contrib.auth.decorators import login_required
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500
)


#import notifications.urls

admin.autodiscover()

urlpatterns = [
    url(
        r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}},
    ),

    url(
        r'^rosetta/',
        include('rosetta.urls'),
    ),

    path(
        'api/',
        include('apps.api.urls', namespace='api'),
    ),

    path(
        'ratings/',
        include('star_ratings.urls', namespace='ratings')
    ),

    url(
        r'^jsreverse/$',
        views.urls_js, name='js_reverse'
    ),
]

urlpatterns += i18n_patterns(
    url(
        r'^nested_admin/',
        include('nested_admin.urls'),
    ),

    url(
        r'^admin/',
        admin.site.urls,
    ),

    url(
        r'^impersonate/',
        include('impersonate.urls'),
    ),

    path(
        'summernote/',
        include('django_summernote.urls'),
    ),

    url(
        r'^accounts/',
        include("apps.accounts.urls", namespace='accounts'),
    ),

    path(
        'directmessages/',
        include("apps.directmessages.urls")
    ),

    url(
        r'^category/destination/(?P<slug>\w+)',
        DetailDestinationView.as_view(),
        name='view_detail_destination',
    ),

    url(
        r'^search/',
        CategoriesView.as_view(),
        name='search_category',
    ),

    url(
        r'^category/(?P<alias>\w+)',
        CategoriesView.as_view(),
        name='view_category',
    ),

    path(
        'community/',
        include('apps.community.urls'),
        name='community',
    ),

    path(
        'paypal/',
        include('apps.payments.paypal.urls'),
    ),

    path(
        'dashboard/',
        include("apps.destinations.urls",
                namespace='dashboard'),
    ),

    path(
        'advertisements/',
        include("apps.advertisements.urls",
                namespace='advertisements'),
    ),

    path(
        'personal-search/',
        SaveSearchView.as_view(),
        name='personal-search',
    ),

    path(
        'make-booking/',
        BookingSaveView.as_view(),
        name='make-booking',
    ),

    path(
        'delete-register/',
        DeleteRegisterView.as_view(),
        name='delete-register',
    ),

    path(
        'setting-privacy/',
        PrivacySettingView.as_view(),
        name='setting-privacy',
    ),

    url(r'^get-itinerary/(?P<slug>\w+)',
        getItineraryPDF.as_view(),
        name='get_itinerary'),

    url(r'contact-us',
        ContactUs.as_view(),
        name='contact-us'),

    url(
        r'^',
        include('cms.urls'),
        name='index',
    ),

    #url('^inbox/notifications/',
    #    include(notifications.urls, namespace='notifications')),


)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom Defaults Pages https://docs.djangoproject.com/en/2.1/ref/views/#error-views
handler400 = 'apps.landing_page.views.pag_400_bad_request'
handler403 = 'apps.landing_page.views.pag_403_permission_denied'
handler404 = 'apps.landing_page.views.pag_404_page_not_found'
handler500 = 'apps.landing_page.views.pag_500_server_error'

travel/apps/destinations/views/maps.py
import logging
from django.http import JsonResponse
from django.utils.translation import gettext_lazy as _
from django.shortcuts import (
    render,
    get_object_or_404,
)
from django.http import QueryDict
from apps.destinations.forms import DestinationMapForm

from apps.destinations.models import Destination, DestinationMap
from django.views.generic import (
    View,
)
from apps.destinations.serializers import (
    MapSerializer,
    mapped_errors_form,
)

from apps.utils.mixins import NoCommunityRequiredMixin

logger = logging.getLogger(__name__)

class DestinationMapView(NoCommunityRequiredMixin, View):
    def get(self, request):
        form_map =  DestinationMapForm()
        form_map.fields['destination'].queryset = Destination.objects.filter(
                user=request.user,
                map=None)
        destination = DestinationMap.objects.filter(destination__user=request.user.id)
        return render(request,'destinations/map/maps.html',{'form_map':form_map, 'destination':destination})

    def post(self,request):
        form_map = DestinationMapForm(request.POST)
        if form_map.is_valid():
            if form_map.save() :
                destination = DestinationMap.objects.filter(destination__user=request.user.id)
                return render(request,'destinations/map/maps.html',{'form_map':form_map, 'destination':destination})
        else:
            return JsonResponse(
                {
                'error':mapped_errors_form(form_map),
                'status':False
                },
                safe=False,
            )

    def delete(self,request):
        pk_map= QueryDict(request.body)
        maps = get_object_or_404(DestinationMap, pk=pk_map['pk'])
        if maps.delete() :
            return JsonResponse(
                {
                'status':True
                },
                safe=False,
            )


class MapListView(View):
    def get(self, request):
        if request.is_ajax():
            if 'destiny' in request.GET:
                maps = DestinationMap.objects.all() \
                .filter(destination__user=request.user.id) \
                .filter(destination=request.GET['destiny'])
                return JsonResponse(
                    MapSerializer(maps),
                    safe=False,
                    )
            else:
                return JsonResponse({},
                    safe=False,
                    )

travel/apps/destinations/views/visitor.py
from django.contrib.gis.geoip2 import GeoIP2
from django.conf import settings
from django.http import JsonResponse
from django.views.generic import (
    View,
)
from django.utils.translation import gettext_lazy as _

from apps.destinations.models import (
	Destination,
	DestinationVisitor
)
from apps.destinations.utils import get_client_ip

class VisitorView(View):
    def get(self, request):
    	geo_ip = GeoIP2()
    	if settings.DEBUG :
    		ip_visitor = "72.14.207.99"
    		data_visitor = geo_ip.city(ip_visitor)
    	else:
    		ip_visitor = get_client_ip(request)
    		data_visitor = geo_ip.city(str(ip_visitor))
    	try:
	    	DestinationVisitor.objects.create(
	    		destination = Destination.objects.get(pk=request.GET['destination']),
	    		ip_address  = ip_visitor,
	    		dma_code =data_visitor['dma_code'] ,
	    		country_code = data_visitor['country_code'],
	    		country_name =data_visitor['country_name']
	    	)
	    	return JsonResponse({},safe=False,status=200)
    	except Exception as e:
    		return JsonResponse({},safe=False,status=500)

travel/apps/destinations/templates/dashboard/dashboard_email.html
{% load static i18n destinations_tags %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta name="viewport" content="width=device-width" />
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>{% trans "New Messages" %}</title>
    <style>
/* -------------------------------------
    GLOBAL
    A very basic CSS reset
------------------------------------- */
* {
    margin: 0;
    padding: 0;
    font-family: "Helvetica Neue", "Helvetica", Helvetica, Arial, sans-serif;
    box-sizing: border-box;
    font-size: 14px;
}

img {
    max-width: 100%;
}

body {
    -webkit-font-smoothing: antialiased;
    -webkit-text-size-adjust: none;
    width: 100% !important;
    height: 100%;
    line-height: 1.6;
}

/* Let's make sure all tables have defaults */
table td {
    vertical-align: top;
}

/* -------------------------------------
    BODY & CONTAINER
------------------------------------- */
body {
    background-color: #f6f6f6;
}

.body-wrap {
    background-color: #f6f6f6;
    width: 100%;
}

.container {
    display: block !important;
    max-width: 600px !important;
    margin: 0 auto !important;
    /* makes it centered */
    clear: both !important;
}

.content {
    max-width: 600px;
    margin: 0 auto;
    display: block;
    padding: 20px;
}

/* -------------------------------------
    HEADER, FOOTER, MAIN
------------------------------------- */
.main {
    background: #fff;
    border: 1px solid #e9e9e9;
    border-radius: 3px;
}

.content-wrap {
    padding: 20px;
}

.content-block {
    padding: 0 0 20px;
}

.header {
    width: 100%;
    margin-bottom: 20px;
}

.footer {
    width: 100%;
    clear: both;
    color: #999;
    padding: 20px;
}
.footer a {
    color: #999;
}
.footer p, .footer a, .footer unsubscribe, .footer td {
    font-size: 12px;
}

/* -------------------------------------
    TYPOGRAPHY
------------------------------------- */
h1, h2, h3 {
    font-family: "Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif;
    color: #000;
    margin: 40px 0 0;
    line-height: 1.2;
    font-weight: 400;
}

h1 {
    font-size: 32px;
    font-weight: 500;
}

h2 {
    font-size: 24px;
}

h3 {
    font-size: 18px;
}

h4 {
    font-size: 14px;
    font-weight: 600;
}

p, ul, ol {
    margin-bottom: 10px;
    font-weight: normal;
}
p li, ul li, ol li {
    margin-left: 5px;
    list-style-position: inside;
}

/* -------------------------------------
    LINKS & BUTTONS
------------------------------------- */
a {
    color: #1ab394;
    text-decoration: underline;
}

.btn-primary {
    text-decoration: none;
    color: #FFF;
    background-color: #1ab394;
    border: solid #1ab394;
    border-width: 5px 10px;
    line-height: 2;
    font-weight: bold;
    text-align: center;
    cursor: pointer;
    display: inline-block;
    border-radius: 5px;
    text-transform: capitalize;
}

/* -------------------------------------
    OTHER STYLES THAT MIGHT BE USEFUL
------------------------------------- */
.last {
    margin-bottom: 0;
}

.first {
    margin-top: 0;
}

.aligncenter {
    text-align: center;
}

.alignright {
    text-align: right;
}

.alignleft {
    text-align: left;
}

.clear {
    clear: both;
}

/* -------------------------------------
    ALERTS
    Change the class depending on warning email, good email or bad email
------------------------------------- */
.alert {
    font-size: 16px;
    color: #fff;
    font-weight: 500;
    padding: 20px;
    text-align: center;
    border-radius: 3px 3px 0 0;
}
.alert a {
    color: #fff;
    text-decoration: none;
    font-weight: 500;
    font-size: 16px;
}
.alert.alert-warning {
    background: #f8ac59;
}
.alert.alert-bad {
    background: #ed5565;
}
.alert.alert-good {
    background: #1ab394;
}

/* -------------------------------------
    INVOICE
    Styles for the billing table
------------------------------------- */
.invoice {
    margin: 40px auto;
    text-align: left;
    width: 80%;
}
.invoice td {
    padding: 5px 0;
}
.invoice .invoice-items {
    width: 100%;
}
.invoice .invoice-items td {
    border-top: #eee 1px solid;
}
.invoice .invoice-items .total td {
    border-top: 2px solid #333;
    border-bottom: 2px solid #333;
    font-weight: 700;
}

/* -------------------------------------
    RESPONSIVE AND MOBILE FRIENDLY STYLES
------------------------------------- */
@media only screen and (max-width: 640px) {
    h1, h2, h3, h4 {
        font-weight: 600 !important;
        margin: 20px 0 5px !important;
    }

    h1 {
        font-size: 22px !important;
    }

    h2 {
        font-size: 18px !important;
    }

    h3 {
        font-size: 16px !important;
    }

    .container {
        width: 100% !important;
    }

    .content, .content-wrap {
        padding: 10px !important;
    }

    .invoice {
        width: 100% !important;
    }
}
    </style>
</head>

<body>

<table class="body-wrap">
    <tr>
        <td></td>
        <td class="container" width="600">
            <div class="content">
                <table class="main" width="100%" cellpadding="0" cellspacing="0">
                    <tr>
                        <td class="alert alert-good">
                            <b>{% trans "Travelposting" %}</b>
                        </td>
                    </tr>
                    <tr>
                        <td class="content-wrap">
                            <table width="100%" cellpadding="0" cellspacing="0">
                                <tr>
                                    <td class="content-block">
                                        {% trans 'You have a new message:' %}
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        <b> {% trans 'User: ' %} </b>{{ user }}<br>
                                        <b> {% trans 'Full Name:' %}</b> {{ name }}<br>
                                        <br>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        <a href="https://travelposting.com/dashboard/mailbox" class="btn-primary">{% trans "See all your messages" %}</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="content-block">
                                        <a href="https://travelposting.com/">https://travelposting.com</a>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr>
                </table>
                <div class="footer">

                </div></div>
        </td>
        <td></td>
    </tr>
</table>

</body>
</html>

travel/apps/destinations/templates/dashboard/user_register_total.html
<div class="padding center">
  <ul class="inline bordered">
    {% for statistic in module.children %}
    <li>
      <div class="big">{{ statistic.value }}</div>
      <div class="dim">{{ statistic.title }}</div>
    </li>
    {% endfor %}
  </ul>
</div>

travel/apps/destinations/templates/dashboard/widgets.html
{% load i18n static charts%}
<div class="row">
    <div class="col-lg-3">
        <div class="ibox ">
            <div class="ibox-title">
                <div class="ibox-tools">
                    <span class="float-right">
                    <span style="font-size: 1.5em; color: #23c6c8;">
                    <i class="fa fa-plane"></i>
                    </span>
                </div>
                <h5>{% trans "Destinations" %}</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins">{{ dashboard_list.destination_count }}</h1>
                <small>
                <a href="{% url 'destinations:list' %}" class="label label-info">
                {% trans "Show Destinations" %}
                </a>
                </small>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox ">
            <div class="ibox-title">
                <div class="ibox-tools">
                    <span class="float-right">
                    <span style="font-size: 1.5em; color: #1c84c6;">
                    <i class="fa fa-credit-card"></i>
                    </span>
                    </span>
                </div>
                <h5>{% trans "Booking" %}</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins">{{ dashboard_list.booking_count }}</h1>
                <small>
                <a href="{% url 'destinations:booking-list' %}" class="label label-success">
                {% trans "Show Bookings" %}
                </a>
                </small>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox ">
            <div class="ibox-title">
                <div class="ibox-tools">
                    <span class="label label-primary float-right">{% trans "Today" %}</span>
                </div>
                <h5>{% trans "User Connected" %}</h5>
            </div>
            <div class="ibox-content">
                <h1 class="no-margins">{{ dashboard_list.user_last }}</h1>
                <div class="stat-percent font-bold text-navy"><i class="fa fa-level-up"></i></div>
                <small>{% trans "Number of users connected" %}</small>
            </div>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="ibox ">
            <div class="ibox-title">
                <div class="ibox-tools">
                    <span class="label label-danger float-right">{% trans "Low value" %}</span>
                </div>
                <h5>{% trans "User activity" %}</h5>
            </div>
            <div class="ibox-content">
                <h4 class="no-margins">{{ request.user.last_login }}</h4>
                <br>
                <div class="stat-percent font-bold text-success"> <i class="fa fa-level-up"></i></div>
                <small>{% trans "Last Visit" %}</small>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-lg-4">
        <div class="ibox ">
            <div class="ibox-title">
                <h5>{% trans "Visitor by Destinations" %}</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link">
                    <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content table-responsive">
                <table class="table table-hover no-margins">
                    <thead>
                        <tr>
                            <th>{% trans "Destinations" %}</th>
                            <th>{% trans "Last Visit" %}</th>
                            <th>{% trans "Number visits" %}</th>
                        </tr>
                    </thead>
                    <tbody>
                        {%for statis_destine in statis_destinies%}
                        <tr>
                            <td><small>{{ statis_destine.name }}</small></td>
                            <td>{{ statis_destine.last_visit|default_if_none:"" }}</td>
                            <td><span class="label label-primary">{{ statis_destine.visitor_count|default_if_none:"" }}</span></td>
                        </tr>
                        {% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="col-lg-8">
        <div class="ibox ">
            <div class="ibox-title">
                <h5>{% trans "Number of visits per country" %}</h5>
                <div class="ibox-tools">
                    <a class="collapse-link">
                    <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="close-link">
                    <i class="fa fa-times"></i>
                    </a>
                </div>
            </div>
            <div class="ibox-content">
                <div class="row">
                    <div class="col-lg-5">
                        <table class="table table-hover margin bottom">
                            <thead>
                                <tr>
                                    <th class="text-center">{% trans "IP Address" %}</th>
                                    <th>{% trans "Location" %}</th>
                                    <th class="text-center">{% trans "Total visits from country" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for visits in last_visits %}
                                <tr>
                                    <td class="text-center">{{ visits.last_ip }}</td>
                                    <td> {{ visits.location|default:_('Unknown') }} </td>
                                    <td class="text-center"> {% total_visits visits.location %}</td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                    <div class="col-lg-7">
                        <div id="world-map" style="height: 300px;"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>