travel/apps/accounts/urls.py
from django.urls import path
from apps.accounts import views
from django.contrib.auth.views import logout_then_login


app_name = 'accounts'

urlpatterns = [
    path(
        'activate/complete/',
        views.isuccess,
         name='activate-complete',
    ),

    path(
        'activate/<str:activation_key>/',
        views.ActivateAccountView.as_view(),
        name='activate',
    ),

    path(
        'register/',
        views.RegisterView.as_view(),
        name='register',
    ),

    path('register/<valor>/<int>', views.RegisterView.as_view(), name='register2'),

    path(
        'login/',
        views.LoginView.as_view(),
        name='login',
    ),

    path(
        'logout/',
        logout_then_login,
        name='logout',
    ),

    path(
        'register/success/',
        views.isuccess,
        name='register-complete',
    ),

    path(
        'password_reset/',
        views.PasswordResetView.as_view(),
        name='password-reset',
    ),

    path(
        'reset/<uidb64>/<token>/',
        views.PasswordResetConfirmView.as_view(),
        name='password-reset-confirm',
    ),

    path(
        'password_reset/done/',
        views.PasswordResetDoneView.as_view(),
        name='password-reset-done',
    ),

    path(
        'reset/complete/',
        views.PasswordResetCompleteView.as_view(),
        name='password-reset-complete',
    ),

    path(
        'password_change/',
        views.PasswordChangeView.as_view(),
        name='password-change',
    ),

    path(
        'password_change/done/',
        views.PasswordChangeDoneView.as_view(),
        name='password-change-done',
    ),

    path(
        'user/<int:pk>/details/',
        views.CustomUserDetailView.as_view(),
        name='user-details',
    ),

    path(
        'user/<int:pk>/update/',
        views.CustomUserUpdateView.as_view(),
        name='user-update',
    ),

    path(
        'user/<int:pk>/complete/',
        views.CompleteProfileView.as_view(),
        name='user-complete-profile',
    ),
    path(
        'user/<int:pk>/update/',
        views.CustomUserUpdateView.as_view(),
        name='user-update',
    ),
]

travel/apps/destinations/urls.py
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import path

from apps.accounts.models import CustomerUser
from apps.destinations.charts import (
    BookingCharts,
    DashboardIndex,
    DestinationCharts,

)
from apps.destinations.views.visitor import (
    VisitorView,
)

from apps.destinations.views.destination import (
    AgencyAddView,
    AgencyDeleteView,
    AgencyAddExistingUserView,
    AgencyUpdateView,
    AgencyView,
    DestinationListView,
    DestinationCreateView,
    DestinationDetailView,
    DestinationUpdateView,
    DestinationDeleteView,
    GalleryListView,
    VideoListView,
    OptionTabDataTemplateAjaxView,
    ItineraryCreateView,
    ItineraryUpdateView,
    ItineraryView,
    RequestDeleteView,
    RequestManagerView,
    RequestProcessView,
    RequestView,
    SocialNetworkListView,
    SocialNetworkUpdateView,
    MailboxView,
    MailboxAdd,
    MailboxReply,
    MailboxDetail,
    MailboxSent,
    messageView,
    LeaderView,
    LeaderAddView,
    LeaderAddExistingUserView,
    LeaderDeleteView,
    DocumentView,
    DocumentAdd,
    DocumentUpdateView,
    FileDocumentsView,
    SearchDocumentsView
)

from apps.destinations.views.booking import (
    BookingListView,
    BookingSaveStat,
    UpdateBooking
)

from apps.destinations.views.maps import (
    DestinationMapView,
    MapListView,
)


def nocommunity_access(function=None, redirect_field_name=REDIRECT_FIELD_NAME, login_url=None):
    actual_decorator = user_passes_test(
        lambda u: u.is_authenticated,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    nocom_decorator = user_passes_test(
        lambda u: u.is_authenticated and not u.is_community,
        login_url=login_url,
        redirect_field_name=redirect_field_name
    )
    if function:
        return actual_decorator(function) and  nocom_decorator(function)
    return actual_decorator and nocom_decorator



app_name = 'destinations'
urlpatterns = [
    path(
        '',
        nocommunity_access(DashboardIndex),
        name='dashboard-index',
    ),
    path(
        'documents',
        nocommunity_access(DocumentView.as_view()),
        name='documents',
    ),
    path('documents/add/',
        nocommunity_access(DocumentAdd.as_view()),
        name='documents-add'
    ),
    path(
        'documents/delete',
        nocommunity_access(DocumentView.as_view()),
        name='documents-delete',
    ),
    path(
        'documents/<int:pk>/update/',
        nocommunity_access(DocumentUpdateView.as_view()),
        name='documents-update',
    ),
    path(
        'files/',
        nocommunity_access(FileDocumentsView.as_view()),
        name='files-documents',
    ),
    path(
        'files/search',
        nocommunity_access(SearchDocumentsView.as_view()),
        name='files-search',
    ),
    path(
        'managers',
        nocommunity_access(LeaderView.as_view()),
        name='manager',
    ),
    path(
        'managers/add/existing',
        nocommunity_access(LeaderAddExistingUserView.as_view()),
        name='manager-add-existing'
    ),
    path(
        'managers/add/',
        nocommunity_access(LeaderAddView.as_view()),
        name='manager-add',
    ),
    path(
        'managers/<int:pk>/delete',
        nocommunity_access(LeaderDeleteView.as_view()),
        name='manager-delete'
    ),
    path(
        'agencies/list',
        nocommunity_access(AgencyView.as_view()),
        name='agencies',
    ),
    path(
        'agencies/add/existing',
        nocommunity_access(AgencyAddExistingUserView.as_view()),
        name='agency-add-existing'
    ),
    path(
        'agencies/add',
        nocommunity_access(AgencyAddView.as_view()),
        name='agency-add'
    ),
    path(
        'agencies/<int:pk>/delete',
        nocommunity_access(AgencyDeleteView.as_view()),
        name='agency-delete'
    ),

    path(
        'agencies/<int:pk>/',
        nocommunity_access(AgencyUpdateView.as_view()),
        name='agency-edit'
    ),
    path(
        'mailbox',
        nocommunity_access(MailboxView.as_view()),
        name='mailbox',
    ),
    path(
        'mailbox/sent',
        nocommunity_access(MailboxSent.as_view()),
        name='mailbox-sent',
    ),
    path(
        'mailbox/delete-mail',
        nocommunity_access(MailboxView.as_view()),
        name='delete-mail',
    ),
    path(
        'mailbox/add',
        nocommunity_access(MailboxAdd.as_view()),
        name='mailbox-add',
    ),
    path(
        'mailbox/reply/<int>',
        nocommunity_access(MailboxReply.as_view()),
        name='mailbox-reply',
    ),
    path(
        'mailbox/<int>',
        nocommunity_access(MailboxDetail.as_view()),
        name='mailbox-detail'
    ),

    path(
        'list',
        nocommunity_access(DestinationListView.as_view()),
        name='list',
    ),

    path(
        'create/',
        nocommunity_access(DestinationCreateView.as_view()),
        name='create',
    ),

    path(
        '<int:pk>/create/',
        nocommunity_access(DestinationDetailView.as_view()),
        name='detail',
    ),

    path(
        '<int:pk>/update/',
        nocommunity_access(DestinationUpdateView.as_view()),
        name='update',
    ),

    path(
        '<int:pk>/delete/',
        nocommunity_access(DestinationDeleteView.as_view()),
        name='delete',
    ),

    path(
        'social-network/',
        nocommunity_access(SocialNetworkListView.as_view()),
        name='social-network',
    ),
    path(
        'social-network/delete-setting',
        nocommunity_access(SocialNetworkListView.as_view()),
        name='delete-setting',
    ),
    path(
        '<int:pk>/up/',
        nocommunity_access(SocialNetworkUpdateView.as_view()),
        name='update-social',
    ),

    path(
        '<int:pk>/gallery/',
        nocommunity_access(GalleryListView.as_view()),
        name='gallery-list',
    ),

    path(
        '<int:pk>/video/',
        nocommunity_access(VideoListView.as_view()),
        name='video-list',
    ),

    path(
        'option/<int:pk>/template/',
        nocommunity_access(OptionTabDataTemplateAjaxView.as_view()),
        name='option-template',
    ),

    path(
        'itinerary/get-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='get-itinerary',
    ),

    path(
        'itinerary/add-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='add-itinerary',
    ),
    path(
        'itinerary/update-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='update-itinerary',
    ),
    path(
        'itinerary/delete-itinerary',
        nocommunity_access(ItineraryView.as_view()),
        name='delete-itinerary',
    ),
    path(
        'itinerary/create/',
        nocommunity_access(ItineraryCreateView.as_view()),
        name='itinerary-create',
    ),
    path(
        'itinerary/<pk>/edit/',
        nocommunity_access(ItineraryUpdateView.as_view()),
        name='itinerary-edit',
    ),

    path(
        'itinerary/',
        nocommunity_access(ItineraryView.as_view()),
        name='itinerary-list',
    ),

    path(
        'booking-list/',
        nocommunity_access(BookingListView.as_view()),
        name='booking-list',
    ),

    path(
        'booking-charts/',
        nocommunity_access(BookingCharts),
        name='booking-charts',
    ),

    path(
        'booking-save/',
        nocommunity_access(BookingSaveStat.as_view()),
        name='booking-save',
    ),

    path(
        'update-booking/',
        nocommunity_access(UpdateBooking.as_view()),
        name='update-booking',
    ),

    path(
        'destination-charts/',
        nocommunity_access(DestinationCharts),
        name='destination-charts',
    ),

    path(
        'maps/get-list',
        nocommunity_access(MapListView.as_view()),
        name='list-maps',
    ),

    path(
        'maps/add-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='add-map',
    ),
    path(
        'maps/update-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='update-map',
    ),
    path(
        'maps/delete-map',
        nocommunity_access(DestinationMapView.as_view()),
        name='delete-map',
    ),


    path(
        'maps/',
        nocommunity_access(DestinationMapView.as_view()),
        name='destination-map',
    ),

    path(
        'message/',
        nocommunity_access(messageView.as_view()),
        name='send_message',
    ),

    path(
        'requests/manager',
        nocommunity_access(RequestManagerView.as_view()),
        name='requests_manager',
    ),
    path(
        'requests/<int:pk>/approve/',
        nocommunity_access(RequestProcessView.as_view(action='approve')),
        name='requests_approve',
    ),

    path(
        'requests/<int:pk>/reject/',
        nocommunity_access(RequestProcessView.as_view(action='reject')),
        name='requests_reject',
    ),

    path(
        'requests/<int:pk>/delete/',
        nocommunity_access(RequestDeleteView.as_view()),
        name='requests_delete',
    ),

    path(
        'requests/',
        nocommunity_access(RequestView.as_view()),
        name='requests',
    ),

    path(
        'visitor/',
        nocommunity_access(VisitorView.as_view()),
        name='visitor',
    ),
]

travel/apps/payments/paypal/urls.py
from django.urls import path

from apps.payments.paypal.views import CancelRedirectView, ApproveRedirectView

app_name = 'paypal'
urlpatterns = [
    path(
        'subscription/approved',
        ApproveRedirectView.as_view(),
        name='subscription-approved',
    ),

    path(
        'subscription/cancel',
        CancelRedirectView.as_view(),
        name='subscription-cancel',
    ),

]

travel/config/urls.py
from cms.sitemaps import CMSSitemap
from django.conf import settings
from django.conf.urls import include, url
from django.urls import path
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django_js_reverse import views
from apps.landing_page.views import (
    CategoriesView,
    DetailDestinationView,
    SaveSearchView,
    DeleteRegisterView,
    PrivacySettingView,
    getItineraryPDF,
    ContactUs,
)

from apps.destinations.views.booking import BookingSaveView
from django.contrib.auth.decorators import login_required
from django.conf.urls import (
    handler400,
    handler403,
    handler404,
    handler500
)


#import notifications.urls

admin.autodiscover()

urlpatterns = [
    url(
        r'^sitemap\.xml$',
        sitemap,
        {'sitemaps': {'cmspages': CMSSitemap}},
    ),

    url(
        r'^rosetta/',
        include('rosetta.urls'),
    ),

    path(
        'api/',
        include('apps.api.urls', namespace='api'),
    ),

    path(
        'ratings/',
        include('star_ratings.urls', namespace='ratings')
    ),

    url(
        r'^jsreverse/$',
        views.urls_js, name='js_reverse'
    ),
]

urlpatterns += i18n_patterns(
    url(
        r'^nested_admin/',
        include('nested_admin.urls'),
    ),

    url(
        r'^admin/',
        admin.site.urls,
    ),

    url(
        r'^impersonate/',
        include('impersonate.urls'),
    ),

    path(
        'summernote/',
        include('django_summernote.urls'),
    ),

    url(
        r'^accounts/',
        include("apps.accounts.urls", namespace='accounts'),
    ),

    path(
        'directmessages/',
        include("apps.directmessages.urls")
    ),

    url(
        r'^category/destination/(?P<slug>\w+)',
        DetailDestinationView.as_view(),
        name='view_detail_destination',
    ),

    url(
        r'^search/',
        CategoriesView.as_view(),
        name='search_category',
    ),

    url(
        r'^category/(?P<alias>\w+)',
        CategoriesView.as_view(),
        name='view_category',
    ),

    path(
        'community/',
        include('apps.community.urls'),
        name='community',
    ),

    path(
        'paypal/',
        include('apps.payments.paypal.urls'),
    ),

    path(
        'dashboard/',
        include("apps.destinations.urls",
                namespace='dashboard'),
    ),

    path(
        'advertisements/',
        include("apps.advertisements.urls",
                namespace='advertisements'),
    ),

    path(
        'personal-search/',
        SaveSearchView.as_view(),
        name='personal-search',
    ),

    path(
        'make-booking/',
        BookingSaveView.as_view(),
        name='make-booking',
    ),

    path(
        'delete-register/',
        DeleteRegisterView.as_view(),
        name='delete-register',
    ),

    path(
        'setting-privacy/',
        PrivacySettingView.as_view(),
        name='setting-privacy',
    ),

    url(r'^get-itinerary/(?P<slug>\w+)',
        getItineraryPDF.as_view(),
        name='get_itinerary'),

    url(r'contact-us',
        ContactUs.as_view(),
        name='contact-us'),

    url(
        r'^',
        include('cms.urls'),
        name='index',
    ),

    #url('^inbox/notifications/',
    #    include(notifications.urls, namespace='notifications')),


)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

# Custom Defaults Pages https://docs.djangoproject.com/en/2.1/ref/views/#error-views
handler400 = 'apps.landing_page.views.pag_400_bad_request'
handler403 = 'apps.landing_page.views.pag_403_permission_denied'
handler404 = 'apps.landing_page.views.pag_404_page_not_found'
handler500 = 'apps.landing_page.views.pag_500_server_error'

travel/apps/destinations/views/visitor.py
from django.contrib.gis.geoip2 import GeoIP2
from django.conf import settings
from django.http import JsonResponse
from django.views.generic import (
    View,
)
from django.utils.translation import gettext_lazy as _

from apps.destinations.models import (
	Destination,
	DestinationVisitor
)
from apps.destinations.utils import get_client_ip

class VisitorView(View):
    def get(self, request):
    	geo_ip = GeoIP2()
    	if settings.DEBUG :
    		ip_visitor = "72.14.207.99"
    		data_visitor = geo_ip.city(ip_visitor)
    	else:
    		ip_visitor = get_client_ip(request)
    		data_visitor = geo_ip.city(str(ip_visitor))
    	try:
	    	DestinationVisitor.objects.create(
	    		destination = Destination.objects.get(pk=request.GET['destination']),
	    		ip_address  = ip_visitor,
	    		dma_code =data_visitor['dma_code'] ,
	    		country_code = data_visitor['country_code'],
	    		country_name =data_visitor['country_name']
	    	)
	    	return JsonResponse({},safe=False,status=200)
    	except Exception as e:
    		return JsonResponse({},safe=False,status=500)

travel/apps/destinations/templates/dashboard/leaders/_agencies.html
{% extends 'destinations/base.html' %}
{% load static i18n destinations_tags static %}
{% block title %}{% trans 'Agencies - Travelposting' %}{% endblock %}
{% block extracss %}
<!-- FooTable -->
<link href="{% static 'dashboard/css/plugins/footable/footable.core.css' %}" rel="stylesheet">
<link href="{% static 'dashboard/css/plugins/iCheck/custom.css' %}" rel="stylesheet">
{% endblock extracss%}
{% block content %}
<div id="page-wrapper" class="gray-bg">
    {% include 'destinations/navbar_top.html' %}
    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h3>{% trans "Agencies List"%}</h3>
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="/es/dashboard/">Inicio</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url "dashboard:manager" %}">{% trans "Managers"%}</a>
                </li>
                <li class="breadcrumb-item active">
                    <strong>{% trans "Agencies"%}</strong>
                </li>
            </ol>
        </div>
    </div>
    <!-- Vista interna-->
    <div class="wrapper wrapper-content">
        <div class="row">
            <div class="col-lg-6">
                <div class="widget style1 navy-bg">
                    <div class="row">
                        <div class="col-4">
                            <i class="fa fa-users fa-4x"></i>
                        </div>
                        <div class="col-8 text-right">
                            <span> {% trans "Travelposting Leaders" %} </span>
                            <h2 class="font-bold">
                                {{ conteo }}
                            </h2>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="widget style1 lazur-bg">
                    <div class="row">
                        <div class="col-4">
                            <i class="fa fa-users fa-4x"></i>
                        </div>
                        <div class="col-8 text-right">
                            <span> {% trans "Registered Agencies" %} </span>
                            <h2 class="font-bold">
                                {{ conteo_agency }}
                            </h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12 animated fadeInRight">

                <div class="ibox">
                    <div class="ibox-title">
                        <h5>{% trans "Manager Plataform"%}</h5>
                        <div class="ibox-tools">
                            <div class="btn-group">
                                <button onclick="window.location.href='{% url "dashboard:manager" %}'"   class="btn btn-outline btn-primary" type="button"><i class="fa fa-see"></i> <b class="color:white;">{% trans "See manager"%}</b></button>
                                <button class="btn btn-outline btn-primary" type="button"  data-toggle="modal" data-target="#myModal"><i class="fa fa-plus"></i> <b class="color:white;">{% trans "add agency"%}</b></button>
                                <div class="modal inmodal" id="myModal" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content animated bounceInRight">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                                <h4 class="modal-title">{% trans "Choose an option" %}</h4>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="text-center">
                                                            <a href="{% url 'dashboard:agency-add' %}" class="text-info">
                                                                <i class="fa fa-plus fa-5x"></i>
                                                                <p class="font-bold"> 
                                                                    {% trans "Add new Agency" %}
                                                                </p>
                                                            </a>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6">
                                                        <div class="text-center">
                                                            <a href="{% url 'dashboard:agency-add-existing' %}" class="text-info">
                                                                <i class="fa fa-address-card fa-5x"></i>
                                                                <p class="font-bold">{% trans "Add existing user" %}</p>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                                <button class="btn btn-outline btn-danger" type="button"  data-toggle="modal" data-target="#myManagerModal"> <i class="fa fa-plus"></i> <b>{% trans "add new Manager"%}</b></button>
                                <div class="modal inmodal" id="myManagerModal" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content animated bounceInRight">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                                <h4 class="modal-title">{% trans "Choose an option" %}</h4>
                                            </div>
                                            <div class="modal-body">
                                                <div class="row">
                                                    <div class="col-lg-6">
                                                        <div class="text-center">
                                                            <a href="{% url 'destinations:manager-add' %}" class="text-info">
                                                                <i class="fa fa-plus fa-5x"></i>
                                                                <p class="font-bold"> 
                                                                    {% trans "Add new Manager" %}
                                                                </p>
                                                            </a>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6">
                                                        <div class="text-center">
                                                            <a href="{% url 'destinations:manager-add-existing' %}" class="text-info">
                                                                <i class="fa fa-address-card fa-5x"></i>
                                                                <p class="font-bold">{% trans "Add existing user" %}</p>
                                                            </a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <input type="text" class="form-control form-control-sm m-b-xs" id="filter"
                            placeholder="{% trans 'Search manager country' %}">
                        <table class="table table-striped" data-page-size="8" data-filter=#filter>
                            <thead>
                                <tr>
                                    <th>{% trans "Full Name" %}</th>
                                    <th>{% trans "Email" %}</th>
                                    <th>{% trans "Country" %}</th>
                                    <th>{% trans "Phone" %}</th>
                                    <th>{% trans "Actions "%}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for users in users_agency %}
                                <tr class="gradeA">
                                    <td>{{users.get_full_name }}</td>
                                    <td>{{ users.email}}</td>

                                    <td>
                                        {{ users.get_country_display}}
                                    </td>
                                    <td>
                                        {% trans "It does not have" as nophone %}    
                                        {{ users.mobile|default_if_none:nophone }}    
                                    </td>

                                    <td>
                                        <a href="{% url 'accounts:user-details' users.id %}" class="btn btn-outline btn-primary  btn-xs"> {% trans "See" %}
                                        </a>
                                        <a href="{% url 'accounts:user-update' users.id %}" class="btn btn-outline btn-primary btn-xs ">
                                            {% trans "Edit" %}
                                        </a>
                                        <button class="btn btn-outline btn-danger btn-xs" type="button"  data-toggle="modal" data-target="#myModalDelete"><i class="fa fa-minus"></i> <b class="color:white;">{% trans "Delete" %}</b></button>
                                <div class="modal inmodal" id="myModalDelete" tabindex="-1" role="dialog" aria-hidden="true">
                                    <div class="modal-dialog">
                                        <div class="modal-content animated bounceInRight">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                                                <h4 class="modal-title">{{ users }}</h4>
                                            </div>
                                            <div class="modal-body">
                                                <p>
                                                  {% blocktrans %}
                                                    Are you sure you want to delete the agency {{ users}}?
                                                  {% endblocktrans %}
                                                </p>
                                            </div>
                                            <div class="modal-footer">
                                                    <form method="post"
                                                          action="{% url 'dashboard:agency-delete' users.pk %}">{% csrf_token %}
                                                            <button type="submit"  class="btn btn-danger ">
                                                                    {% trans "Yes" %}
                                                            </button>
                                                            <button  data-dismiss="modal" class="btn">
                                                                {% trans "No" %}
                                                            </button>
                                                </form>
                                            </div>

                                        </div>
                                    </div>
                                </div>

                                        </span>
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                            <tfoot>
                                <tr>
                                    <td colspan="5">
                                        <ul class="pagination float-right"></ul>
                                    </td>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    <!-- Fin vista interna-->
    {% include 'destinations/footer.html' %}
</div>
{% endblock %}